Feature bl 7949 add post eu rfr categories
dvsa/mot-public-api pull request #62
Opened 2018-07-25 15:42 UTC by ryszardm-kainos

2018-07-30 07:51 UTC, przemos requested changes

2018-07-30 07:51 UTC, przemos commented on api/src/main/java/uk/gov/dvsa/mot/app/TradeServiceRequestHandler.java
> +        logger.trace("Entering setVehicleResponseMapperFactory");
do you think those traces will be useful for the future ? If not, let's remove it

2018-07-30 07:51 UTC, przemos commented on api/src/main/java/uk/gov/dvsa/mot/app/TradeServiceRequestHandler.java
> +            logger.info("Requesting version: " + versionHeader);
let's keep invocations as they should be logger.info("Requesting version: {}, versionHeader)

2018-07-30 07:51 UTC, przemos commented on api/src/main/java/uk/gov/dvsa/mot/app/TradeServiceRequestHandler.java
>                  logger.info("Trade API request for vehicle_id = " + request.getVehicleId());
use logger invocation with placeholder as above, please

2018-07-30 07:51 UTC, przemos commented on api/src/main/java/uk/gov/dvsa/mot/trade/api/TradeServiceRequest.java
> +                if (headerEntry.getParam().equals(headerKey)) {
just a reminder that it is generally safer to call constant.equals(variable) instead of variable.equals(constant) due to null-safety.

2018-07-30 07:51 UTC, przemos commented on api/src/main/java/uk/gov/dvsa/mot/trade/api/response/mapper/VehicleResponseMapperFactory.java
> +        if (version == null) {
it would be good to log out the final choice of a mapper as a way of then investigating which versions are still in use and which not, to ultimately deprecate and remove the latter. Naturally, using logger level that will spit out this data without override.

2018-07-30 07:51 UTC, przemos commented on api/src/main/java/uk/gov/dvsa/mot/trade/api/response/mapper/VehicleV4ResponseMapper.java
> +        if (!StringUtils.isNullOrEmpty(rfrAndAdvisoryItem.getType()) && rfrAndAdvisoryItem.getType().equals("FAIL")) {
Constant extraction to at least class level. As much as "FAIL" can tell what the going is, "PE" below does not come immediately obvious.

2018-07-30 07:51 UTC, przemos commented on api/src/test/integration/java/uk/gov/dvsa/mot/app/GetTradeMotTestsByRegistrationAndMake.java
>              System.out.println(output.toString());
do we need system out ?

2018-07-30 07:54 UTC, ryszardm-kainos commented on api/src/main/java/uk/gov/dvsa/mot/app/TradeServiceRequestHandler.java
> +        logger.trace("Entering setVehicleResponseMapperFactory");
removed

2018-07-30 07:56 UTC, ryszardm-kainos commented on api/src/main/java/uk/gov/dvsa/mot/app/TradeServiceRequestHandler.java
> +            logger.info("Requesting version: " + versionHeader);
In a better world where such method signatures exist :( Can add `String.format` for this

2018-07-30 08:42 UTC, ryszardm-kainos commented on api/src/main/java/uk/gov/dvsa/mot/trade/api/TradeServiceRequest.java
> +                if (headerEntry.getParam().equals(headerKey)) {
amended

2018-07-30 08:44 UTC, ryszardm-kainos commented on api/src/test/integration/java/uk/gov/dvsa/mot/app/GetTradeMotTestsByRegistrationAndMake.java
>              System.out.println(output.toString());
Those are not really tests from what I can see - no assertions here. Those are just prepared handler launchers to run the TAPI locally

2018-07-30 08:58 UTC, ryszardm-kainos commented on api/src/main/java/uk/gov/dvsa/mot/trade/api/response/mapper/VehicleResponseMapperFactory.java
> +        if (version == null) {
added info log for that

2018-07-30 09:02 UTC, ryszardm-kainos commented on api/src/main/java/uk/gov/dvsa/mot/trade/api/response/mapper/VehicleV4ResponseMapper.java
> +        if (!StringUtils.isNullOrEmpty(rfrAndAdvisoryItem.getType()) && rfrAndAdvisoryItem.getType().equals("FAIL")) {
extracted

2018-07-31 13:07 UTC, przemos requested changes

2018-07-31 13:07 UTC, przemos commented on api/src/main/java/uk/gov/dvsa/mot/app/TradeServiceRequestHandler.java
> +                logger.info("Trade API request for vehicle_id = {}", vehicleId.toString());
we dont have to call toString, do we ?

2018-07-31 13:07 UTC, przemos commented on api/src/main/java/uk/gov/dvsa/mot/app/VehicleResponseBodyWriter.java
> +            return "json".equalsIgnoreCase(subtype) || subtype.startsWith("json")
can we do classic:
if(customCheck()) { return doCustomCheck();} else {return super.hasMatchingMediaType(mediaType);}

2018-07-31 13:07 UTC, przemos commented on api/src/test/unit/java/uk/gov/dvsa/mot/trade/api/response/mapper/MockVehicleDataHelper.java
> +                getRfr("FAIL", "PE"),
missed extraction

2018-07-31 13:07 UTC, przemos commented on api/src/test/unit/java/uk/gov/dvsa/mot/trade/api/response/mapper/VehicleV4ResponseMapperTest.java
> +            if (rfr.getType().equals("FAIL") && !rfr.getDeficiencyCategoryCode().equals("PE")) {
missed extraction

2018-07-31 13:07 UTC, przemos commented on api/src/test/unit/java/uk/gov/dvsa/mot/trade/api/response/mapper/MockVehicleDataHelper.java
> +                getRfr("ADVISORY", "PE"),
missed extraction

2018-07-31 13:14 UTC, ryszardm-kainos commented on api/src/main/java/uk/gov/dvsa/mot/app/TradeServiceRequestHandler.java
> +                logger.info("Trade API request for vehicle_id = {}", vehicleId.toString());
toString removed

2018-07-31 13:29 UTC, ryszardm-kainos commented on api/src/main/java/uk/gov/dvsa/mot/app/VehicleResponseBodyWriter.java
> +            return "json".equalsIgnoreCase(subtype) || subtype.startsWith("json")
done

2018-07-31 13:29 UTC, ryszardm-kainos commented on api/src/test/unit/java/uk/gov/dvsa/mot/trade/api/response/mapper/MockVehicleDataHelper.java
> +                getRfr("FAIL", "PE"),
extracted

2018-07-31 13:29 UTC, ryszardm-kainos commented on api/src/test/unit/java/uk/gov/dvsa/mot/trade/api/response/mapper/VehicleV4ResponseMapperTest.java
> +            if (rfr.getType().equals("FAIL") && !rfr.getDeficiencyCategoryCode().equals("PE")) {
extracted

2018-07-31 13:29 UTC, ryszardm-kainos commented on api/src/test/unit/java/uk/gov/dvsa/mot/trade/api/response/mapper/MockVehicleDataHelper.java
> +                getRfr("ADVISORY", "PE"),
extracted

2018-07-31 14:03 UTC, przemos approved these changes

2018-07-31 14:23 UTC, merged